-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 19:48:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Databasv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Databasv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Databasv2` DEFAULT CHARACTER SET utf8 ;
USE `Databasv2` ;

-- -----------------------------------------------------
-- Table `Databasv2`.`PersonalData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`PersonalData` (
  `PersonalDataId` INT NOT NULL AUTO_INCREMENT,
  `PersonaDataName` VARCHAR(100) NOT NULL,
  `PersonalDataPhone` VARCHAR(100) NOT NULL,
  `PersonalDataEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PersonalDataId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Manufactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Manufactor` (
  `ManufactorerId` INT NOT NULL AUTO_INCREMENT,
  `ManufactorerName` VARCHAR(100) NOT NULL,
  `ManufactorerAddressHQ` VARCHAR(100) NOT NULL,
  `ManufactoerPhoneHQ` INT NOT NULL,
  `PersonalDataId` INT NOT NULL,
  PRIMARY KEY (`ManufactorerId`),
  INDEX `fk_Manufactor_ContactPerson1_idx` (`PersonalDataId` ASC) VISIBLE,
  CONSTRAINT `fk_Manufactor_ContactPerson1`
    FOREIGN KEY (`PersonalDataId`)
    REFERENCES `Databasv2`.`PersonalData` (`PersonalDataId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Supplier` (
  `SupplierId` INT NOT NULL AUTO_INCREMENT,
  `SupplierName` VARCHAR(100) NOT NULL,
  `SupplierAddress` VARCHAR(100) NOT NULL,
  `SupplierPhone` VARCHAR(100) NOT NULL,
  `SupplierEmail` VARCHAR(100) NOT NULL,
  `PersonalDataId` INT NOT NULL,
  PRIMARY KEY (`SupplierId`),
  INDEX `fk_Supplier_ContactPerson1_idx` (`PersonalDataId` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_ContactPerson1`
    FOREIGN KEY (`PersonalDataId`)
    REFERENCES `Databasv2`.`PersonalData` (`PersonalDataId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Sparepart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Sparepart` (
  `SparepartId` INT NOT NULL AUTO_INCREMENT,
  `SparepartName` VARCHAR(45) NOT NULL,
  `ManufactorId` INT NOT NULL,
  `SupplierId` INT NOT NULL,
  `SparepartDescription` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`SparepartId`),
  INDEX `fk_Sparepart_Manufactor1_idx` (`ManufactorId` ASC) VISIBLE,
  INDEX `fk_Sparepart_Supplier1_idx` (`SupplierId` ASC) VISIBLE,
  CONSTRAINT `fk_Sparepart_Manufactor1`
    FOREIGN KEY (`ManufactorId`)
    REFERENCES `Databasv2`.`Manufactor` (`ManufactorerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sparepart_Supplier1`
    FOREIGN KEY (`SupplierId`)
    REFERENCES `Databasv2`.`Supplier` (`SupplierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`CustomerType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`CustomerType` (
  `CustomerTypeId` INT NOT NULL AUTO_INCREMENT,
  `CustmerType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CustomerTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Customer` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(100) NOT NULL,
  `CustomerAddress` VARCHAR(100) NOT NULL,
  `CustomerPhone` VARCHAR(100) NOT NULL,
  `CustomerEmail` VARCHAR(100) NOT NULL,
  `CustmerTypeId` INT NOT NULL,
  PRIMARY KEY (`CustomerId`),
  INDEX `fk_Customer_CustomerType1_idx` (`CustmerTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_CustomerType1`
    FOREIGN KEY (`CustmerTypeId`)
    REFERENCES `Databasv2`.`CustomerType` (`CustomerTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Cars` (
  `CarsId` INT NOT NULL AUTO_INCREMENT,
  `CarsRegNo` VARCHAR(100) NOT NULL,
  `CarsManufactor` VARCHAR(100) NOT NULL,
  `CarsModel` VARCHAR(100) NOT NULL,
  `CarsColor` VARCHAR(100) NOT NULL,
  `CustomerId` INT NOT NULL,
  PRIMARY KEY (`CarsId`),
  INDEX `fk_Cars_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `Databasv2`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Store` (
  `StoreId` INT NOT NULL AUTO_INCREMENT,
  `StoreName` VARCHAR(100) NOT NULL,
  `StoreAddress` VARCHAR(100) NOT NULL,
  `StorePhone` VARCHAR(100) NOT NULL,
  `StoreEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`StoreId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Orders` (
  `OrdersId` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATE NOT NULL,
  `OrderTime` TIME NOT NULL,
  `Store_` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  PRIMARY KEY (`OrdersId`),
  INDEX `fk_Orders_Store1_idx` (`Store_` ASC) VISIBLE,
  INDEX `fk_Orders_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Store1`
    FOREIGN KEY (`Store_`)
    REFERENCES `Databasv2`.`Store` (`StoreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `Databasv2`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Store_Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Store_Employee` (
  `StoreEmployeeId` INT NOT NULL AUTO_INCREMENT,
  `StoreId` INT NOT NULL,
  `PersonalDataId` INT NOT NULL,
  PRIMARY KEY (`StoreEmployeeId`),
  INDEX `fk_Store_Employee_Store1_idx` (`StoreId` ASC) VISIBLE,
  INDEX `fk_Store_Employee_ContactPerson1_idx` (`PersonalDataId` ASC) VISIBLE,
  CONSTRAINT `fk_Store_Employee_Store1`
    FOREIGN KEY (`StoreId`)
    REFERENCES `Databasv2`.`Store` (`StoreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_Employee_ContactPerson1`
    FOREIGN KEY (`PersonalDataId`)
    REFERENCES `Databasv2`.`PersonalData` (`PersonalDataId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`Inventory` (
  `InventoryId` INT NOT NULL,
  `StoreId` INT NOT NULL,
  `InventoryLocation` VARCHAR(100) NOT NULL,
  `InventoryQTY` INT NOT NULL,
  `InventoryCriticalLevel` INT NOT NULL,
  `InventotyAutomaticOrder` INT NOT NULL,
  `InventoryQTYAutomaticOrder` INT NOT NULL,
  `InventoryETA` DATE NOT NULL,
  `SparepartId` INT NOT NULL,
  PRIMARY KEY (`InventoryId`),
  INDEX `fk_Inventory_Store1_idx` (`StoreId` ASC) VISIBLE,
  INDEX `fk_Inventory_Sparepart1_idx` (`SparepartId` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Store1`
    FOREIGN KEY (`StoreId`)
    REFERENCES `Databasv2`.`Store` (`StoreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventory_Sparepart1`
    FOREIGN KEY (`SparepartId`)
    REFERENCES `Databasv2`.`Sparepart` (`SparepartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`CarsSparepart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`CarsSparepart` (
  `CarsID` INT NOT NULL,
  `SparepartId` INT NOT NULL,
  PRIMARY KEY (`CarsID`, `SparepartId`),
  INDEX `fk_Cars_has_Sparepart_Sparepart1_idx` (`SparepartId` ASC) VISIBLE,
  INDEX `fk_Cars_has_Sparepart_Cars1_idx` (`CarsID` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_has_Sparepart_Cars1`
    FOREIGN KEY (`CarsID`)
    REFERENCES `Databasv2`.`Cars` (`CarsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_has_Sparepart_Sparepart1`
    FOREIGN KEY (`SparepartId`)
    REFERENCES `Databasv2`.`Sparepart` (`SparepartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Databasv2`.`OrdersSparepart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Databasv2`.`OrdersSparepart` (
  `OrdersId` INT NOT NULL,
  `SparepartId` INT NOT NULL,
  `OrdersAmount` INT NOT NULL,
  PRIMARY KEY (`OrdersId`, `SparepartId`),
  INDEX `fk_Orders_has_Sparepart_Sparepart1_idx` (`SparepartId` ASC) VISIBLE,
  INDEX `fk_Orders_has_Sparepart_Orders1_idx` (`OrdersId` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_has_Sparepart_Orders1`
    FOREIGN KEY (`OrdersId`)
    REFERENCES `Databasv2`.`Orders` (`OrdersId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Sparepart_Sparepart1`
    FOREIGN KEY (`SparepartId`)
    REFERENCES `Databasv2`.`Sparepart` (`SparepartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
